### ISSUE TITLE
The mqtt trigger can not work with other trigger?

### ISSUE THREAD

**Issue by xiaocode** [spinkube/spin-trigger-mqtt#34]
I want to use spin-trigger-mqtt with any other trigger, such as http or cron.
It shows that: 
```
Error: metadata error: missing required metadata "trigger"
A trigger exited unexpectedly. Terminating.
```

**Comment by karthik2804** [comment]
I investigated this a bit and yes currently it does not work with other triggers. I will open a PR shortly to fix this.
