### ISSUE TITLE
Rename to `spin-trigger-mqtt`?

### ISSUE THREAD

**Issue by fibonacci1729** [spinkube/spin-trigger-mqtt#8]
Hi @suneetnangia!

As i was playing around with this repository i noticed the repository name is `spin-mqtt-trigger-sdk`. Would you be opposed to renaming to `spin-trigger-mqtt`? The naming convention of `spin-trigger-<TRIGGER_TYPE>` seems to be the implicit pattern followed by [spin-trigger-cron](https://github.com/fermyon/spin-trigger-cron) and [spin-trigger-sqs](https://github.com/fermyon/spin-trigger-sqs).

Wdyt?

**Comment by suneetnangia** [comment]
Sounds good @fibonacci1729, thanks.

**Comment by itowlson** [comment]
Who has access to do this?  @suneetnangia are you still a maintainer/admin?  Or do we need someone with org permissions?

**Comment by suneetnangia** [comment]
> Who has access to do this? @suneetnangia are you still a maintainer/admin? Or do we need someone with org permissions?

I am a maintainer but it seems I cannot change name, do not see the settings section for this repo.

**Comment by itowlson** [comment]
@radu-matei @endocrimes @vdice Who has the power to rename repos in this org?

**Comment by endocrimes** [comment]
I can do it 👍

**Comment by radu-matei** [comment]
@suneetnangia you should now also be an admin of the repo, which means you can rename the repo.

**Comment by suneetnangia** [comment]
Renamed.
